-- Snowflake: GOLD.DIABETES_PREVALENCE_STATE, built from SILVER.BRFSS_CLEAN.
-- Direct translation of sql/databricks/04_gold.sql - same definitions, same columns.

USE DATABASE BRFSS;

CREATE OR REPLACE TABLE GOLD.DIABETES_PREVALENCE_STATE AS
SELECT
  c.STATE_FIPS,
  s.LABEL AS STATE_NAME,
  c.SURVEY_YEAR,
  -- Snowflake does not support the FILTER (WHERE ...) clause Databricks/Spark uses on
  -- aggregates (tested directly, real syntax error) - CASE WHEN inside the aggregate is
  -- the portable equivalent: COUNT(CASE WHEN cond THEN 1 END) counts only matching rows
  -- (NULL is not counted), SUM(CASE WHEN cond THEN x END) sums only matching rows.
  COUNT(CASE WHEN c.DIABETES_CODE IN (1,2,3,4) THEN 1 END)            AS VALID_RESPONDENTS,
  COUNT(CASE WHEN c.DIABETES_CODE = 1 THEN 1 END)                     AS DIABETES_YES,
  SUM(CASE WHEN c.DIABETES_CODE = 1 THEN c.FINAL_WEIGHT END)          AS WEIGHTED_YES_SUM,
  SUM(CASE WHEN c.DIABETES_CODE IN (1,2,3,4) THEN c.FINAL_WEIGHT END) AS WEIGHTED_VALID_SUM,
  100.0 * SUM(CASE WHEN c.DIABETES_CODE = 1 THEN c.FINAL_WEIGHT END)
        / SUM(CASE WHEN c.DIABETES_CODE IN (1,2,3,4) THEN c.FINAL_WEIGHT END)   AS PREVALENCE_WEIGHTED_PCT,
  100.0 * COUNT(CASE WHEN c.DIABETES_CODE = 1 THEN 1 END)
        / COUNT(CASE WHEN c.DIABETES_CODE IN (1,2,3,4) THEN 1 END)              AS PREVALENCE_UNWEIGHTED_PCT,
  COUNT(CASE WHEN c.DIABETES_CODE IN (7,9) OR c.DIABETES_CODE IS NULL THEN 1 END) AS EXCLUDED_DONT_KNOW_REFUSED_BLANK
FROM SILVER.BRFSS_CLEAN c
-- state_fips is '06' style (zero-padded); the codebook's own codes are unpadded ('6'),
-- hence the cast-to-int-then-back-to-string round trip, same as the Databricks join.
LEFT JOIN REF.CODEBOOK_VALUES s
  ON s.VARIABLE = '_STATE' AND s.CODE = TO_VARCHAR(CAST(c.STATE_FIPS AS INT))
GROUP BY c.STATE_FIPS, s.LABEL, c.SURVEY_YEAR;

-- Verification - same checks as Databricks
SELECT COUNT(*) FROM GOLD.DIABETES_PREVALENCE_STATE;
SELECT COUNT(*) FROM GOLD.DIABETES_PREVALENCE_STATE WHERE STATE_NAME IS NULL;
SELECT SUM(VALID_RESPONDENTS) FROM GOLD.DIABETES_PREVALENCE_STATE;
SELECT SUM(VALID_RESPONDENTS) + SUM(EXCLUDED_DONT_KNOW_REFUSED_BLANK) FROM GOLD.DIABETES_PREVALENCE_STATE;
SELECT 100.0 * SUM(WEIGHTED_YES_SUM) / SUM(WEIGHTED_VALID_SUM) AS NATIONAL_PREVALENCE_WEIGHTED_PCT
FROM GOLD.DIABETES_PREVALENCE_STATE;
