table gold_diabetes_prevalence_state
	lineageTag: f121ed27-9954-40fd-8890-f559adaedcd4

	column state_fips
		dataType: string
		lineageTag: a9a84e48-1833-45f4-b9a3-81a41fab0eab
		summarizeBy: none
		sourceColumn: state_fips

		annotation SummarizationSetBy = Automatic

	column survey_year
		dataType: int64
		formatString: 0
		lineageTag: bae2aede-feee-4173-85f3-6a8ffc79bcb8
		summarizeBy: sum
		sourceColumn: survey_year

		annotation SummarizationSetBy = Automatic

	column valid_respondents
		dataType: int64
		formatString: 0
		lineageTag: b993aa7e-e7b4-46e9-92a8-76a22bf7076f
		summarizeBy: sum
		sourceColumn: valid_respondents

		annotation SummarizationSetBy = Automatic

	column diabetes_yes
		dataType: int64
		formatString: 0
		lineageTag: f972b7ff-38e1-4285-99fb-6c7cc50ac3a0
		summarizeBy: sum
		sourceColumn: diabetes_yes

		annotation SummarizationSetBy = Automatic

	column weighted_yes_sum
		dataType: double
		lineageTag: 415bc931-4c53-44a2-80ab-f6a393ade098
		summarizeBy: sum
		sourceColumn: weighted_yes_sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_valid_sum
		dataType: double
		lineageTag: ebd4a97a-6549-49e4-a6b5-9c5a995aaf69
		summarizeBy: sum
		sourceColumn: weighted_valid_sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prevalence_weighted_pct
		dataType: double
		lineageTag: 4513f9df-ccd1-484a-8297-6961c8a73c4e
		summarizeBy: sum
		sourceColumn: prevalence_weighted_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column excluded_dont_know_refused_blank
		dataType: int64
		formatString: 0
		lineageTag: 3710dc3e-46a6-4540-95db-c122b3b4f9bb
		summarizeBy: sum
		sourceColumn: excluded_dont_know_refused_blank

		annotation SummarizationSetBy = Automatic

	column state_name
		dataType: string
		lineageTag: 191efe2a-fffa-46bd-8609-6644ecdd2958
		summarizeBy: none
		sourceColumn: state_name
		dataCategory: StateOrProvince

		annotation SummarizationSetBy = Automatic

	measure 'National Prevalence %' = ```
			DIVIDE(SUM(gold_diabetes_prevalence_state[weighted_yes_sum]), SUM(gold_diabetes_prevalence_state[weighted_valid_sum]))
			```
		formatString: 0.0%
		lineageTag: 46de57b8-ff22-4a90-98eb-f0b8720c4a6e

	measure 'States Covered' = DISTINCTCOUNT(gold_diabetes_prevalence_state[state_fips])
		formatString: 0
		lineageTag: ebd1a81e-a24c-4b6b-893c-6c0dfff93a92

	measure 'Years Covered' = DISTINCTCOUNT(gold_diabetes_prevalence_state[survey_year])
		formatString: 0
		lineageTag: 9e8197f1-89eb-4ee3-9746-85df1d8c9ea0

	partition gold_diabetes_prevalence_state = m
		mode: import
		source =
			let
				Source = DatabricksMultiCloud.Catalogs("dbc-93916528-90f8.cloud.databricks.com", "/sql/1.0/warehouses/6cd9ffe6ba1a7c82", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", Protocol=null]),
				workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				lakeflow_demo_Schema = workspace_Database{[Name="lakeflow_demo",Kind="Schema"]}[Data],
				gold_diabetes_prevalence_state_View = lakeflow_demo_Schema{[Name="gold_diabetes_prevalence_state",Kind="View"]}[Data],
				ref_Schema = workspace_Database{[Name="ref",Kind="Schema"]}[Data],
				codebook_values_Table = ref_Schema{[Name="codebook_values",Kind="Table"]}[Data],
				state_labels = Table.SelectRows(codebook_values_Table, each [variable] = "_STATE"),
				Added_join_key = Table.AddColumn(gold_diabetes_prevalence_state_View, "state_code_join", each Text.From(Number.From([state_fips])), type text),
				Merged_with_labels = Table.NestedJoin(Added_join_key, {"state_code_join"}, state_labels, {"code"}, "StateInfo", JoinKind.LeftOuter),
				Expanded_StateInfo = Table.ExpandTableColumn(Merged_with_labels, "StateInfo", {"label"}, {"state_name"}),
				Removed_join_key = Table.RemoveColumns(Expanded_StateInfo, {"state_code_join"})
			in
				Removed_join_key

	annotation PBI_ResultType = Table
